# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e3e3816fc5962107b28f2bac4af2522d3eadb7aab73a45397b7bff3c4ceb5d22add9761f929785363d79e20f9805350e5e7470cbce28300f1cfcddc8b669349

test:
  secret_key_base: 291842638cca3657cae8410ed768658293595a70d067217b9248a4b9da7debf994fec1963128345749eef9b8e999bfb0e89bf6fd75f7c0ab4efdac019bb8e752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
